version: "3"
services:
  odoo-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
  odoo-dev:
    build: .
    ports:
      - "8069:8069"
    volumes:
      - .:/src
      - /etc/passwd:/etc/passwd:ro
      - /var/tmp/odoo:/var/lib/odoo
    user: ${UID}
    environment:
      PGHOST: odoo-db
      PGUSER: odoo
      PGPASSWORD: odoo
    depends_on:
      - odoo-db
